"use client";
export const dynamic = "force-dynamic";

// Sentinel — Investigation Queue (renamed + restructured from Review
// Queue). Full chain per the vision doc: Observation -> Evidence ->
// AI Analysis -> Confidence -> Suggested Questions -> Suggested Actions
// -> Approve -> Archive. Confidence is always the computed value from
// anomaly.ts, rendered here, never generated by this page.

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";
import { groupFlagsByWorkspace, runAllChecks } from "./lib/anomaly";
import { buildPeerTable } from "./lib/engine";
import { SERIF, T } from "./lib/theme";
import type { AnomalyFlag, FinancialStatement, Investigation, Workspace } from "./lib/types";

const STATUS_LABEL: Record<string, string> = {
  pending: "Pending",
  approved: "Approved",
  edited: "Approved \u00b7 edited",
  rejected: "Rejected",
  archived: "Archived",
};

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: "0.66rem",
        fontWeight: 600,
        letterSpacing: "0.07em",
        textTransform: "uppercase",
        color: T.accent,
        margin: "1rem 0 0.35rem 0",
      }}
    >
      {children}
    </p>
  );
}

function StatusPill({ status }: { status: string }) {
  const color =
    status === "approved" || status === "edited"
      ? T.accent
      : status === "rejected" || status === "archived"
        ? T.ink
        : T.inkSoft;
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        fontSize: "0.68rem",
        fontWeight: 600,
        letterSpacing: "0.05em",
        textTransform: "uppercase",
        padding: "0.28rem 0.7rem",
        border: `1px solid ${color}`,
        color,
      }}
    >
      <span style={{ width: 5, height: 5, background: color }} />
      {STATUS_LABEL[status] ?? status}
    </span>
  );
}

function FlagChip({ flag }: { flag: AnomalyFlag }) {
  return (
    <div
      style={{
        background: T.accentSoft,
        borderLeft: `2px solid ${T.accent}`,
        padding: "0.6rem 0.9rem",
        marginBottom: "0.45rem",
        fontSize: "0.9rem",
      }}
    >
      <span
        style={{
          fontSize: "0.66rem",
          fontWeight: 600,
          letterSpacing: "0.05em",
          textTransform: "uppercase",
          color: T.accent,
          marginRight: "0.55rem",
        }}
      >
        {flag.flag_type}
      </span>
      {flag.description}
    </div>
  );
}

function ConfidenceBar({ score, signals }: { score: number; signals: Record<string, unknown> }) {
  return (
    <div style={{ margin: "0.9rem 0" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
        <span
          style={{
            fontSize: "0.66rem",
            fontWeight: 600,
            letterSpacing: "0.07em",
            textTransform: "uppercase",
            color: T.inkSoft,
          }}
        >
          Confidence
        </span>
        <span style={{ fontFamily: SERIF, fontWeight: 600, fontSize: "1.1rem", color: T.ink }}>
          {score}%
        </span>
      </div>
      <div style={{ height: 4, background: T.rule, marginTop: "0.35rem" }}>
        <div style={{ height: 4, width: `${score}%`, background: T.accent }} />
      </div>
      <p style={{ fontSize: "0.72rem", color: T.inkSoft, marginTop: "0.35rem" }}>
        {String(signals.flag_count)} flag(s) · {String(signals.corroborating_flag_types)} independent
        signal type(s) agreeing · peer set n={String(signals.peer_sample_size)}
      </p>
    </div>
  );
}

const btnBase: React.CSSProperties = {
  fontFamily: "inherit",
  fontSize: "0.85rem",
  fontWeight: 500,
  padding: "0.5rem 1.1rem",
  border: `1px solid ${T.ink}`,
  borderRadius: 3,
  background: "transparent",
  color: T.ink,
  cursor: "pointer",
};
const btnPrimary: React.CSSProperties = { ...btnBase, background: T.ink, color: T.background };

export default function InvestigationQueuePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [statements, setStatements] = useState<FinancialStatement[]>([]);
  const [investigations, setInvestigations] = useState<Map<string, Investigation>>(new Map());
  const [showArchived, setShowArchived] = useState(false);
  const [generating, setGenerating] = useState<string | null>(null);
  const [edits, setEdits] = useState<Record<string, string>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});

  const loadAll = useCallback(async () => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData.session) {
      router.push("/login");
      return;
    }
    const [wsRes, invRes] = await Promise.all([
      supabase.from("sentinel_workspaces").select("*"),
      supabase.from("sentinel_investigations").select("*"),
    ]);
    if (wsRes.error) {
      setError(wsRes.error.message);
      setLoading(false);
      return;
    }
    const ws = (wsRes.data ?? []) as Workspace[];
    setWorkspaces(ws);

    const { data: stmtData, error: stmtError } = await supabase
      .from("sentinel_statements")
      .select("*")
      .in("workspace_id", ws.map((w) => w.id));
    if (stmtError) {
      setError(stmtError.message);
    } else {
      setStatements((stmtData ?? []) as FinancialStatement[]);
    }
    if (!invRes.error) {
      const m = new Map<string, Investigation>();
      for (const inv of (invRes.data ?? []) as Investigation[]) {
        m.set(`${inv.workspace_id}|${inv.period_label}`, inv);
      }
      setInvestigations(m);
    }
    setLoading(false);
  }, [router]);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  if (loading) return <p style={{ color: T.inkSoft }}>Loading Sentinel…</p>;
  if (error) return <p style={{ color: T.ink }}>Could not load data: {error}</p>;

  // Flags don't depend on which workspace is "subject" (that only
  // controls chart highlighting elsewhere) - group by sector, compute
  // once per sector using any workspace in that sector as the anchor.
  const bySector = new Map<string, Workspace[]>();
  for (const w of workspaces) {
    if (!bySector.has(w.sector)) bySector.set(w.sector, []);
    bySector.get(w.sector)!.push(w);
  }
  const allFlags: AnomalyFlag[] = [];
  for (const [sector, sectorWs] of bySector) {
    if (sectorWs.length === 0) continue;
    const rows = buildPeerTable(sectorWs, statements, sectorWs[0].id, "FY");
    allFlags.push(...runAllChecks(rows, sector));
  }
  const groups = groupFlagsByWorkspace(allFlags);

  const notGenerated = groups.filter((g) => !investigations.has(`${g[0].workspace_id}|${g[0].period_label}`)).length;
  const allInvestigations = [...investigations.values()];
  const pending = allInvestigations.filter((i) => i.status === "pending").length;
  const approvedCount = allInvestigations.filter((i) => i.status === "approved" || i.status === "edited").length;
  const rejected = allInvestigations.filter((i) => i.status === "rejected").length;
  const archivedCount = allInvestigations.filter((i) => i.status === "archived").length;

  async function generateDraft(workspaceId: string, periodLabel: string) {
    setGenerating(workspaceId);
    try {
      const { data: sessionData } = await supabase.auth.getSession();
      const token = sessionData.session?.access_token;
      const res = await fetch("/api/sentinel/narrative", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ workspace_id: workspaceId, period_label: periodLabel }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? `Request failed (${res.status})`);
      }
      await loadAll();
    } catch (e) {
      alert(e instanceof Error ? e.message : "Draft generation failed");
    } finally {
      setGenerating(null);
    }
  }

  async function decide(inv: Investigation, decision: "approve" | "reject") {
    const key = `${inv.workspace_id}|${inv.period_label}`;
    const editedText = edits[key] ?? inv.ai_narrative ?? "";
    const reviewerNotes = notes[key] || null;
    const update =
      decision === "approve"
        ? {
            status: editedText === inv.ai_narrative ? "approved" : "edited",
            final_narrative: editedText,
            reviewer_notes: reviewerNotes,
            updated_at: new Date().toISOString(),
          }
        : {
            status: "rejected",
            final_narrative: null,
            reviewer_notes: reviewerNotes,
            updated_at: new Date().toISOString(),
          };
    const { error: updateError } = await supabase.from("sentinel_investigations").update(update).eq("id", inv.id);
    if (updateError) {
      alert(updateError.message);
      return;
    }
    await loadAll();
  }

  async function archive(inv: Investigation) {
    const { error: updateError } = await supabase
      .from("sentinel_investigations")
      .update({ status: "archived", archived_at: new Date().toISOString() })
      .eq("id", inv.id);
    if (updateError) {
      alert(updateError.message);
      return;
    }
    await loadAll();
  }

  async function reopen(inv: Investigation) {
    const { error: updateError } = await supabase
      .from("sentinel_investigations")
      .update({ status: "pending", final_narrative: null, archived_at: null, updated_at: new Date().toISOString() })
      .eq("id", inv.id);
    if (updateError) {
      alert(updateError.message);
      return;
    }
    await loadAll();
  }

  const stats: [string, number][] = [
    ["Not generated", notGenerated],
    ["Pending review", pending],
    ["Approved", approvedCount],
    ["Rejected", rejected],
    ["Archived", archivedCount],
  ];

  const visibleGroups = groups.filter((g) => {
    const inv = investigations.get(`${g[0].workspace_id}|${g[0].period_label}`);
    const isArchived = inv?.status === "archived";
    return showArchived ? true : !isArchived;
  });

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
        <h1 style={{ fontFamily: SERIF, fontWeight: 600, fontSize: "2.1rem", margin: 0 }}>
          Investigation Queue
        </h1>
        <label style={{ fontSize: "0.8rem", color: T.inkSoft, display: "flex", alignItems: "center", gap: 6 }}>
          <input type="checkbox" checked={showArchived} onChange={(e) => setShowArchived(e.target.checked)} />
          Show archived
        </label>
      </div>
      <p
        style={{
          fontSize: "0.7rem",
          fontWeight: 500,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: T.inkSoft,
          margin: "0.45rem 0 1.6rem 0",
        }}
      >
        Observation → Evidence → AI Analysis → Confidence → Approve — nothing below is final until approved
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(5, 1fr)",
          gap: 1,
          background: T.rule,
          border: `1px solid ${T.rule}`,
          marginBottom: "1.75rem",
        }}
      >
        {stats.map(([label, value], i) => (
          <div key={label} style={{ background: T.card, padding: "1rem 1.1rem" }}>
            <p
              style={{
                fontSize: "0.62rem",
                fontWeight: 500,
                letterSpacing: "0.06em",
                textTransform: "uppercase",
                color: T.inkSoft,
                margin: "0 0 0.35rem 0",
              }}
            >
              {label}
            </p>
            <p style={{ fontFamily: SERIF, fontSize: "1.7rem", fontWeight: 500, color: i === 2 ? T.accent : T.ink, margin: 0 }}>
              {value}
            </p>
          </div>
        ))}
      </div>

      {visibleGroups.map((group) => {
        const workspaceId = group[0].workspace_id;
        const companyName = group[0].company_name;
        const periodLabel = group[0].period_label;
        const inv = investigations.get(`${workspaceId}|${periodLabel}`);

        return (
          <div
            key={workspaceId}
            style={{
              background: T.card,
              border: `1px solid ${T.rule}`,
              borderRadius: 3,
              padding: "1.4rem 1.7rem",
              marginBottom: "1rem",
              opacity: inv?.status === "archived" ? 0.6 : 1,
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: "0.8rem" }}>
              <h3 style={{ fontFamily: SERIF, fontWeight: 500, fontSize: "1.25rem", margin: 0 }}>
                {companyName}
                <span style={{ fontFamily: "inherit", fontSize: "0.8rem", color: T.inkSoft, marginLeft: "0.6rem" }}>
                  {group.length} flag{group.length > 1 ? "s" : ""}
                </span>
              </h3>
              {inv && <StatusPill status={inv.status} />}
            </div>

            {group.map((f, i) => (
              <FlagChip key={i} flag={f} />
            ))}

            {!inv && (
              <div style={{ marginTop: "0.9rem" }}>
                <button style={btnPrimary} disabled={generating !== null} onClick={() => generateDraft(workspaceId, periodLabel)}>
                  {generating === workspaceId ? "Investigating \u2014 hypothesis, then peer check\u2026" : "Generate draft narrative"}
                </button>
              </div>
            )}

            {inv && inv.status === "pending" && (
              <div>
                {inv.confidence_score != null && <ConfidenceBar score={inv.confidence_score} signals={inv.confidence_signals} />}
                <Eyebrow>Turn 1 — hypothesis, from the company&apos;s own data</Eyebrow>
                <p style={{ fontSize: "0.93rem", lineHeight: 1.65, margin: 0 }}>{inv.initial_hypothesis}</p>
                <Eyebrow>Turn 2 — draft narrative, checked against peers</Eyebrow>
                <p style={{ fontSize: "0.93rem", lineHeight: 1.65, margin: 0 }}>{inv.ai_narrative}</p>

                {inv.suggested_questions.length > 0 && (
                  <>
                    <Eyebrow>Suggested questions</Eyebrow>
                    <ul style={{ margin: 0, paddingLeft: "1.2rem", fontSize: "0.88rem", lineHeight: 1.7 }}>
                      {inv.suggested_questions.map((q, i) => (
                        <li key={i}>{q}</li>
                      ))}
                    </ul>
                  </>
                )}
                {inv.suggested_actions.length > 0 && (
                  <>
                    <Eyebrow>Suggested actions</Eyebrow>
                    <ul style={{ margin: 0, paddingLeft: "1.2rem", fontSize: "0.88rem", lineHeight: 1.7 }}>
                      {inv.suggested_actions.map((a, i) => (
                        <li key={i}>{a}</li>
                      ))}
                    </ul>
                  </>
                )}

                <textarea
                  value={edits[`${workspaceId}|${periodLabel}`] ?? inv.ai_narrative ?? ""}
                  onChange={(e) =>
                    setEdits((prev) => ({ ...prev, [`${workspaceId}|${periodLabel}`]: e.target.value }))
                  }
                  rows={5}
                  style={{
                    width: "100%",
                    marginTop: "1rem",
                    padding: "0.7rem",
                    fontFamily: "inherit",
                    fontSize: "0.9rem",
                    lineHeight: 1.6,
                    border: `1px solid ${T.rule}`,
                    borderRadius: 3,
                    background: T.background,
                    color: T.ink,
                    resize: "vertical",
                  }}
                />
                <input
                  value={notes[`${workspaceId}|${periodLabel}`] ?? ""}
                  onChange={(e) => setNotes((prev) => ({ ...prev, [`${workspaceId}|${periodLabel}`]: e.target.value }))}
                  placeholder="Reviewer notes (optional)"
                  style={{
                    width: "100%",
                    marginTop: "0.5rem",
                    padding: "0.55rem 0.7rem",
                    fontFamily: "inherit",
                    fontSize: "0.85rem",
                    border: `1px solid ${T.rule}`,
                    borderRadius: 3,
                    background: T.card,
                    color: T.ink,
                  }}
                />
                <div style={{ display: "flex", gap: "0.6rem", marginTop: "0.8rem" }}>
                  <button style={btnPrimary} onClick={() => decide(inv, "approve")}>Approve</button>
                  <button style={btnBase} onClick={() => decide(inv, "reject")}>Reject</button>
                  <button style={btnBase} disabled={generating !== null} onClick={() => generateDraft(workspaceId, periodLabel)}>
                    {generating === workspaceId ? "Regenerating\u2026" : "Regenerate draft"}
                  </button>
                </div>
              </div>
            )}

            {inv && (inv.status === "approved" || inv.status === "edited" || inv.status === "rejected") && (
              <div style={{ marginTop: "0.8rem" }}>
                {inv.status === "rejected" ? (
                  <p style={{ fontSize: "0.85rem", color: T.inkSoft, margin: 0 }}>
                    {inv.reviewer_notes ?? "No notes given."}
                  </p>
                ) : (
                  <>
                    {inv.confidence_score != null && <ConfidenceBar score={inv.confidence_score} signals={inv.confidence_signals} />}
                    <p style={{ fontSize: "0.93rem", lineHeight: 1.65, margin: 0 }}>{inv.final_narrative}</p>
                    {inv.reviewer_notes && (
                      <p style={{ fontSize: "0.8rem", color: T.inkSoft, margin: "0.5rem 0 0 0" }}>
                        Reviewer notes: {inv.reviewer_notes}
                      </p>
                    )}
                  </>
                )}
                <div style={{ display: "flex", gap: "0.6rem", marginTop: "0.8rem" }}>
                  <button style={btnBase} onClick={() => reopen(inv)}>Re-open for review</button>
                  <button style={btnBase} onClick={() => archive(inv)}>Archive</button>
                </div>
              </div>
            )}

            {inv && inv.status === "archived" && (
              <div style={{ marginTop: "0.8rem" }}>
                <p style={{ fontSize: "0.85rem", color: T.inkSoft, margin: 0 }}>
                  Archived {inv.archived_at ? new Date(inv.archived_at).toLocaleDateString("en-IN") : ""}.
                </p>
                <button style={{ ...btnBase, marginTop: "0.6rem" }} onClick={() => reopen(inv)}>Re-open for review</button>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
